import { FileDown } from "lucide-react";
import type {
  BacklinksSearchState,
  BacklinksTabRows,
} from "./backlinksPageTypes";

const DISAVOW_SPAM_THRESHOLD = 40;
const GOOGLE_DISAVOW_URL =
  "https://search.google.com/search-console/disavow-links";

/** Builds a Google-format disavow file from the CURRENTLY LOADED rows with
 * spam score >= threshold. Deliberately never auto-submits: generating the
 * file is safe, uploading it is a human decision (bad disavows hurt). */
export function DisavowExportButton({
  activeTab,
  exportTarget,
  tabRows,
}: {
  activeTab: BacklinksSearchState["tab"];
  exportTarget: string;
  tabRows: BacklinksTabRows;
}) {
  if (activeTab === "pages") return null;
  const candidates =
    activeTab === "domains"
      ? tabRows.referringDomains.flatMap((row) =>
          row.domain !== null && (row.spamScore ?? 0) >= DISAVOW_SPAM_THRESHOLD
            ? [row.domain]
            : [],
        )
      : tabRows.backlinks.flatMap((row) =>
          row.domainFrom !== null &&
          (row.spamScore ?? 0) >= DISAVOW_SPAM_THRESHOLD
            ? [row.domainFrom]
            : [],
        );
  const domains = [...new Set(candidates)].toSorted();

  const download = () => {
    const lines = [
      `# Disavow file for ${exportTarget}`,
      `# Generated by Airspace on ${new Date().toISOString().slice(0, 10)}`,
      `# Domains from the currently loaded rows with spam score >= ${DISAVOW_SPAM_THRESHOLD}.`,
      `# REVIEW EVERY LINE before uploading. Wrongly disavowing good links harms rankings.`,
      `# Upload at: ${GOOGLE_DISAVOW_URL}`,
      "",
      ...domains.map((domain) => `domain:${domain}`),
      "",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `disavow-${exportTarget.replace(/[^a-z0-9.-]/gi, "_")}.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
    window.open(GOOGLE_DISAVOW_URL, "_blank", "noopener");
  };

  return (
    <button
      type="button"
      className="btn btn-ghost btn-sm gap-1.5"
      disabled={domains.length === 0}
      title={
        domains.length === 0
          ? `No loaded rows with spam score >= ${DISAVOW_SPAM_THRESHOLD}. Run Spam review first, and page through if there are more rows.`
          : `Download a disavow file for ${domains.length} spam-scored domains from the loaded rows, and open Google's disavow tool. Review before uploading.`
      }
      onClick={download}
    >
      <FileDown className="size-3.5" />
      Disavow file
      {domains.length > 0 ? (
        <span className="badge badge-xs badge-error border-0 text-error-content">
          {domains.length}
        </span>
      ) : null}
    </button>
  );
}
