import { FileDown } from "lucide-react";
import { downloadFile } from "@/client/lib/download";
import type {
  BacklinksSearchState,
  BacklinksTabRows,
} from "./backlinksPageTypes";

const DISAVOW_SPAM_THRESHOLD = 40;
const GOOGLE_DISAVOW_URL =
  "https://search.google.com/search-console/disavow-links";

/** Builds a Google-format disavow file from the CURRENTLY LOADED rows with
 * spam score >= threshold. Deliberately never auto-submits: generating the
 * file is safe, uploading it is a human decision (bad disavows hurt). */
export function DisavowExportButton({
  activeTab,
  exportTarget,
  tabRows,
  totalRows,
}: {
  activeTab: BacklinksSearchState["tab"];
  exportTarget: string;
  tabRows: BacklinksTabRows;
  /** Total rows in the filtered result set, for partial-coverage warnings:
   * Google's disavow upload REPLACES the whole file, so a page-scoped file
   * must never look complete. */
  totalRows: number | null;
}) {
  if (activeTab === "pages") return null;
  const candidates =
    activeTab === "domains"
      ? tabRows.referringDomains.flatMap((row) =>
          row.domain !== null && (row.spamScore ?? 0) >= DISAVOW_SPAM_THRESHOLD
            ? [row.domain]
            : [],
        )
      : tabRows.backlinks.flatMap((row) =>
          row.domainFrom !== null &&
          (row.spamScore ?? 0) >= DISAVOW_SPAM_THRESHOLD
            ? [row.domainFrom]
            : [],
        );
  const domains = [...new Set(candidates)].toSorted();
  const loadedRows =
    activeTab === "domains"
      ? tabRows.referringDomains.length
      : tabRows.backlinks.length;
  // Partial when the filtered result set is larger than what is loaded:
  // Google's upload replaces the account's ENTIRE file, so shipping a
  // page-one file as if complete silently un-disavows the rest.
  const isPartial = totalRows !== null && totalRows > loadedRows;

  const download = () => {
    const lines = [
      `# Disavow file for ${exportTarget}`,
      `# Generated by Airspace on ${new Date().toISOString().slice(0, 10)}`,
      `# Domains from the currently loaded rows with spam score >= ${DISAVOW_SPAM_THRESHOLD}.`,
      ...(isPartial
        ? [
            `# WARNING: PARTIAL FILE. Only ${loadedRows} of ${totalRows} filtered rows were loaded.`,
            `# Google's disavow upload REPLACES your entire existing file. Page through all`,
            `# rows (raise rows-per-page) and regenerate before uploading, or you will`,
            `# silently un-disavow every domain not in this file.`,
          ]
        : []),
      `# REVIEW EVERY LINE before uploading. Wrongly disavowing good links harms rankings.`,
      `# Upload at: ${GOOGLE_DISAVOW_URL}`,
      "",
      ...domains.map((domain) => `domain:${domain}`),
      "",
    ].join("\n");
    downloadFile(
      lines,
      `disavow-${exportTarget.replace(/[^a-z0-9.-]/gi, "_")}${isPartial ? "-PARTIAL" : ""}.txt`,
      "text/plain",
    );
    window.open(GOOGLE_DISAVOW_URL, "_blank", "noopener");
  };

  return (
    <button
      type="button"
      className="btn btn-ghost btn-sm gap-1.5"
      disabled={domains.length === 0}
      title={
        domains.length === 0
          ? `No loaded rows with spam score >= ${DISAVOW_SPAM_THRESHOLD}. Run Spam review first, and page through if there are more rows.`
          : isPartial
            ? `PARTIAL: only ${loadedRows} of ${totalRows} filtered rows are loaded. The file will carry a warning; page through everything before uploading, because Google replaces the whole disavow file.`
            : `Download a disavow file for ${domains.length} spam-scored domains from the loaded rows, and open Google's disavow tool. Review before uploading.`
      }
      onClick={download}
    >
      <FileDown className="size-3.5" />
      Disavow file
      {domains.length > 0 ? (
        <span
          className={`badge badge-xs border-0 ${isPartial ? "badge-warning text-warning-content" : "badge-error text-error-content"}`}
        >
          {domains.length}
          {isPartial ? "…" : ""}
        </span>
      ) : null}
    </button>
  );
}
